### PR TITLE
Fix #22 - Index name is too long

### LINKED ISSUE #22: Index name is too long
```
$ rails db:migrate
== 20170401172016 CreateSimpleHashtagHashtags: migrating ======================
-- create_table(:simple_hashtag_hashtags)
   -> 0.0342s
== 20170401172016 CreateSimpleHashtagHashtags: migrated (0.0347s) =============

== 20170401172017 CreateSimpleHashtagHashtaggings: migrating ==================
-- create_table(:simple_hashtag_hashtaggings)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Index name 'index_simple_hashtag_hashtaggings_on_hashtaggable_type_and_hashtaggable_id' on table 'simple_hashtag_hashtaggings' is too long; the limit is 64 characters
app_root/db/migrate/20170401172017_create_simple_hashtag_hashtaggings.rb:4:in `change'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
ArgumentError: Index name 'index_simple_hashtag_hashtaggings_on_hashtaggable_type_and_hashtaggable_id' on table 'simple_hashtag_hashtaggings' is too long; the limit is 64 characters
app_root/db/migrate/20170401172017_create_simple_hashtag_hashtaggings.rb:4:in `change'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by jonhue**
Resolves #22

### CODE REVIEW

**Comment by chai2** [comment]
+1 - able to do migration with this fix.

**Comment by azeemh** [comment]
+1 thank you

**Comment by andrewwood2** [comment]
Thank you for this fix. Migration working now.

**Comment by PalermoD** [comment]
Sweet this fix works!

**Pull request closed without merging**
